### ISSUE TITLE
Not deterministic `_src_path` in answers file

### ISSUE THREAD

**Issue by yajo** [KyleKing/copier-template-tester#16]
**Describe the bug**

When running pre-commit on CI, I get failures that I don't get locally:

```
copier-template-tester................................................... Failed
- hook id: copier-template-tester
- files were modified by this hook
Creating: /builds/moduon/ops/dct-private/.ctt/full
[...]
  conflict  .copier-answers.dct-private.yml
 overwrite  .copier-answers.dct-private.yml
[...]
pre-commit hook(s) made changes.
If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`.
To run `pre-commit` as part of git workflow, use `pre-commit install`.
All changes made by hooks:
diff --git a/.ctt/full/.copier-answers.dct-private.yml b/.ctt/full/.copier-answers.dct-private.yml
index 205a1ef..4e44453 100644
--- a/.ctt/full/.copier-answers.dct-private.yml
+++ b/.ctt/full/.copier-answers.dct-private.yml
@@ -1,6 +1,6 @@
 # Changes here will be overwritten by Copier; do NOT edit manually
 _commit: v6.4.0-0
-_src_path: /var/home/yajo/prodevel/dct-private
+_src_path: /builds/moduon/ops/dct-private
user: yajo
org: moduon
```

#**To Reproduce**

Steps and/or code snippet(s) to reproduce the behavior:

1. Configure for pre-commit.
1. run it.
2. Commit it.
3. clone in another directory
4. `pre-commit run -a`

**Expected behavior**

The `_src_path` in the answers file, when it points to the local git directory (always, right?), should get stripped off the absolute paths.

Or maybe just harcode it to "." or similar.

In any case, the output should be deterministic.

**Additional Information**

- `copier_template_tester` Version:
- OS: \[e.g. macOS/Windows\]:
- OS Version \[e.g. Catalina/10\]:

**Comment by KyleKing** [comment]
I ran into that in the test suite, but hadn't considered pre-commit in CI (or on another user's computer for that matter). I think I'll need to resolve the path to the git directory and convert the path to relative like I do here:

https://github.com/KyleKing/copier-template-tester/blob/1ca3a1faa40604143986dfbf0033837dd2759933/tests/helpers.py#L82

I'll open a PR when I'm back next week!

**Comment by KyleKing** [comment]
Looks like it works! Try now with v1.2.2

https://github.com/KyleKing/calcipy_template/commit/f2ba3283e0b79b234ace3cda0dc32b7acaec7941

**Comment by yajo** [comment]
Confirmed, thanks!
