### ISSUE TITLE
Whitespace difference between ctt and normal Copier execution

### ISSUE THREAD

**Issue by yajo** [KyleKing/copier-template-tester#18]
**Describe the bug**

CTT seems to trim 1 ending newline character from the answers file.

#**To Reproduce**

```sh
➤ copier -f copy . .ctt/full/
➤ git diff
diff --git a/.ctt/full/.copier-answers.dct-private.yml b/.ctt/full/.copier-answers.dct-private.yml
index 506021c..94c5bd0 100644
--- a/.ctt/full/.copier-answers.dct-private.yml
+++ b/.ctt/full/.copier-answers.dct-private.yml
@@ -1,6 +1,6 @@
 # Changes here will be overwritten by Copier; do NOT edit manually
-_commit: v7.0.0-0
-_src_path: ../../dct-private
+_commit: v7.0.0
+_src_path: .
 collection_account_full: true
 collection_crm: true
 collection_fishing: true
@@ -15,4 +15,5 @@ collection_project: true
 collection_purchase: true
 collection_receipts: true
 collection_sii: true
-collection_stock: true
\ No newline at end of file
+collection_stock: true
+
```

**Expected behavior**

The first part of the diff is normal: CTT patches `_src_path` and `_commit`, and that's OK.

The last part is not expected. You see that Copier adds the newline at end of file (correctly), which CTT had removed (wrongly).

**Additional Information**

Running `pre-commit run copier-template-tester` removes again newline(s) at the end.

Combining with another hook that fixes EOFs, pre-commit enters an endless loop.

- `copier_template_tester` Version: 1.2.2
- OS: \[e.g. macOS/Windows\]: linux
- OS Version \[e.g. Catalina/10\]: fedora 38

**Comment by KyleKing** [comment]
Thanks for the bug report and you caught me at a good time!

I think I have a fix with `1.2.3rc0`, but I'm debugging another minor issue

**Comment by KyleKing** [comment]
When you have a chance, try `1.2.3` and let me know if that solves it!

**Comment by yajo** [comment]
Working, thanks!
