### ISSUE TITLE
pre-commit always fails after version bumping

### ISSUE THREAD

**Issue by yajo** [KyleKing/copier-template-tester#20]
**Describe the bug**

When I add a new tag to the repo, without changing code, the next time I run `pre-commit run ctt` will fail, because the `_commit` tag will change.

This makes that all new releases of the template are flagged with a ❌ on CI, which is not nice.

#**To Reproduce**

Steps and/or code snippet(s) to reproduce the behavior:

1. Set ctt as a pre-commit hook.
1. Change your template and commit.
2. Add the changes added from CTT and commit.
3. Add a new version tag to the template.
4. Push new tag to repo, see pre-commit CI fail.

**Expected behavior**

The result of rendering the current template should set something reproducible into the `_commit` value of the copier answers file. It shouldn't change depending on the state of tags in the repo, which is something that can change even if the commit doesn't.

Possibly it should be forced to contain a hardcoded value like `_commit: HEAD` or `_commit: DISABLED`.

**Additional Information**

- `copier_template_tester` Version: 1.2.3
- OS: \[e.g. macOS/Windows\]: Linux
- OS Version \[e.g. Catalina/10\]: Fedora 38

**Comment by KyleKing** [comment]
I like the idea of replacing the commit version with `HEAD` because I've also been annoyed with that issue, but hadn't had it impact CI. I'll release a new version this evening with that fix!
