### ISSUE TITLE
When template repo dir is dirty, it copies last tag, not current commit

### ISSUE THREAD

**Issue by yajo** [KyleKing/copier-template-tester#4]
**Describe the bug**

#**To Reproduce**

Steps and/or code snippet(s) to reproduce the behavior:

1. Have a template with git tags.
1. Change something.
2. Commit.
3. Pre-commit hook changes ctt output, pointing to HEAD
4. Fix something
5. Commit again.
6. pre-commit hook changes ctt output to last tag, instead of current HEAD with dirty changes applied.

**Expected behavior**

CTT should always render current template with current dirty changes applied.

**Additional Information**

- `copier_template_tester` Version: 1.0.2
- OS: \[e.g. macOS/Windows\]: Linux
- OS Version \[e.g. Catalina/10\]: Fedora 37

**Comment by KyleKing** [comment]
Hi @yajo, thanks for trying out CTT and the issues!

I wasn't aware of #3, but I think I was running into a similar issue as this one, where I couldn't figure out how to have the staged files included in the output from copier copy.

One workaround might be for the tool to maintain a shadow copy of the repo, commit and tag the changes there, then use that folder as the source for the copy? Do you think there might be an easier way?

**Comment by KyleKing** [comment]
Elaborating on the shadow copy approach. I would probably use the `user_cache_dir` from https://github.com/platformdirs/platformdirs

```py
# This is the shadow clone
ctt_cache='/Users/kyle/Library/Caches/copier-template-tester'
# And this is the directory the user is actually working with
working_dir='$PWD'

# Run git init in working_dir
subprocess.check_output('git init', cwd=working_dir)

# Then for each directory in `ctt.toml`, ignore them here:
unlinked_dirs = {'.git', *ctt_dirs}
# and copy the matches over:
for match in [_m for _m in _working_dir.glob('*') if _m not in unlinked_dirs]:
    # I will also try symlinking instead of copy, but I'm not confident that it would work
    if match.is_dir():
        shutil.copytree(match, ctt_cache / match.name)
	else:
        shutil.copy(match, ctt_cache / match.name)
```

On each pre-commit, first get the latest tag from the working directory, then commit and tag the shadow directory

```sh
LAST_TAG=$(git tag | tail -n 1)  # In local working repository
git add --all && git commit "(ctt)" --no-verify && git tag $LAST_TAG-ctt  # In user_cache
```

Then `ctt` in `pre-commit` would `copier copy` the files from the `user_cache` to the local destination specified in the config

**Comment by yajo** [comment]
Have you tried adding `vcs_ref="HEAD"` to the copy call?

**Comment by KyleKing** [comment]
I think I have that set here, but it seems that the problem is that `copier` dosn't support using the stash:

https://github.com/KyleKing/copier-template-tester/blob/597181d8c37c9956dd4edc0d4e904b8d982a4cdf/copier_template_tester/main.py#no-line

The shadow repo approach proposed above wouldn't strictly need to make tags, but the benefit would be more deterministic file output

**Comment by yajo** [comment]
> the benefit would be more deterministic file output

That's important indeed. Otherwise, each new `pre-commit run` would produce a different `_commit` in the copier answers file.

**Comment by KyleKing** [comment]
I seem to have a working solution for this:

https://github.com/KyleKing/copier-template-tester/blob/f04e89ce3c5fcbf3749a543d4fd309077c1fd9fd/copier_template_tester/_write_output.py#L32-L39

I need to test it a bit more with real projects, but so far has appeared to be pretty stable
